### PR TITLE
Reloading the app when the render process crashes

### PR DESCRIPTION
**Pull request by bennyn**
Suggestion by: https://github.com/electron/electron/issues/6971#issuecomment-242803813

### CODE REVIEW

**Comment by lipis** [comment]
:D

**Comment by bennyn** [comment]
Approved?

**Comment by lipis** [comment]
how could we crash the webContents to simulate/test it :)

`process.crash()` I think crashes the whole thing..

**Comment by lipis** [comment]
I tested it.. and it works.. white page and then reloads :) better than a real crash..

**Pull request merged**
