### PR TITLE
Remove all but the last line from RELEASES file

### PR DESCRIPTION
**Pull request by gregor**

### CODE REVIEW

**Comment by lipis** [comment]
The shorter I could come up with is

```python
with open('RELEASES', 'r+') as f:
  f.readline()
  f.truncate()
```

**Comment by gregor** [comment]
@lipis Just tested this. We need the last line of the file and not the first one though.

**Comment by gregor** [comment]
Code is more like that. Another puzlle to shorten?

````python
with open('RELEASES', 'r+') as f:
  last = f.readlines()[-1]
  f.seek(0)
  f.write(last)
  f.truncate()
````

**Comment by lipis** [comment]
if it's last.. then it looks like that's the one.. :)

**Pull request merged**
