### PR TITLE
Restore minimized window on tray click (#416)

### PR DESCRIPTION
**Pull request by ConorIA**
This is intended to resolve some of the frustration expressed in #416. I have done some local testing, and it seems to be working as expected. ~~Of course, Gnome has some strong focus-stealing protection, so even when I click on the tray badge, it gives me a "Wire is ready" notification instead of bringing the window into focus.~~ It should probably be tested on other DEs.

Update: I was browsing some other [FLOSS code](https://github.com/nylas/nylas-mail/blob/3111c166b8c949cf2a5ef60392d83a53e782ebed/src/browser/window-manager.es6) (shoutouts to the Nylas folks!), and copied their solution. This should work now. 

~~Should we stick the `windowManager.getPrimaryWindow()` into a `var` though? (or `const` or `let` ... still don't know what the role of each is) The way it is written now, we're calling the function no less than 8 times!~~

Update 2: I tried sticking this into a function in the `windowManager.js` file. ~~I am not sure about passing arguments in Javascript. I imagine there is some way to call `showPrimaryWindow` on click without wrapping it in an additional function to use `windowManager.getPrimaryWindow()`. I tried a couple of things, e.g. putting the call to `getPrimaryWindow()` inside the `showPrimaryWindow` function, but it gave me errors.~~

Update 3: I guess I can't use a named function as the `click:` response? All seems to be in order (more or less) now. Happy to get feedback and test results.

### CODE REVIEW

**Comment by gregor** [comment]
@lipis If this works we should also hook it up to the notification clicks in https://github.com/wireapp/wire-desktop/blob/5d759b0e17340ead54e9a3a543c2bbf351a23b38/electron/main.js#L127 as people have been complaining that the app is not always put to the foreground then.

**Comment by ConorIA** [comment]
@gregor, I've just added an additional commit that sticks this into two spots in `main.js`: on notification click, and on launching a second instance.

**Comment by gregor** [comment]
@ConorIA Thanks for adding it to the mentioned use cases as well. Back from vacation and reliving what I missed while I was gone just now.

**Comment by ConorIA** [comment]
No problem. Hope you had a relaxing vacation! 🌊🚢🌴

**Pull request merged**
