### PR TITLE
Disable asar for Linux

### PR DESCRIPTION
**Pull request by maximbaz**
This is a temporary workaround for atom/node-spellchecker#49, as suggested by @ConorIA in #334. 

I confirm that it does fix the issue.

Disabling only for Linux since the original bug describes this as a Linux-only issue, though I didn't verify this.

### CODE REVIEW

**Comment by ConorIA** [comment]
So fast! See also: #147.

**Comment by ConorIA** [comment]
Strangely on my machine I still can't get the spellchecker to work. I wonder what I'm missing.

**Comment by ConorIA** [comment]
I figured out what was wrong on my machine ... no love for Canadian English! But, when we disable asar, I can use the same solution as the packager for Atom on Arch used (https://github.com/atom/spell-check/issues/129#issuecomment-223385570).

**Comment by ConorIA** [comment]
Note that instead of `"asar": false`, we could use `"asarUnpack": "node_modules/spellchecker"`. 
In fact, `electron-builder`'s wiki says that node modules that need to be unpacked will be automatically detected, so I will report this as an issue over there.

**Comment by lipis** [comment]
So what do you guys say.. shall I merge this one? Will it work?

**Comment by lipis** [comment]
Spell checker works on my Ubuntu when running it with `npm start` but I can't build it :/

**Comment by maximbaz** [comment]
This definitely fixes the issue for me for the release build.

> Note that instead of "asar": false, I used "asarUnpack": "node_modules/spellchecker/vendor".

I'd like to hear @ConorIA's comments on this, should we go with the `asarUnpack` instead? Does it have some benefits? What would you prefer?

And in general, I'm not sure if we are treating this as a temporary workaround, or we will leave it permanently as asked in #147? If we keep it forever for the sake of #147, then the `"asar": false` is the way to go, I think.

**Comment by lipis** [comment]
Updated everything and it looks like it worked for me as well. So I think I'll go ahead and merge this one.

**Comment by lipis** [comment]
If anything we can fix it later! Thanks guys..

**Comment by ConorIA** [comment]
@maximbaz, I just offered `asarUnpack` as an alternative because `electron-builder` makes noise when we build with asar disabled: 

```
⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
```

I think a full disable will give us the opportunity to appease tray-icon sticklers though, so I think the current merge is a safe bet.

**Pull request merged**
