### PR TITLE
feat: import/export

### PR DESCRIPTION
**Pull request by ffflorian**

### CODE REVIEW

**Comment by gregor** [comment]
@bennyn Wants to use bits of this PR for other purposes.

**Comment by ffflorian** [comment]
@gregor That's why I didn't delete the branch.

**Comment by gregor** [comment]
Just adding a comment as this is unlikely to be general knowledge - in order to avoid an accidental, undesired cleanup.

**Comment by bennyn** [comment]
We can create a GitHub label for cases like this. :)

**Comment by ffflorian** [comment]
Done. :slightly_smiling_face:

**Comment by bennyn** [comment]
@atomrc Do you still have the branch where you added Spectron for testing? If we can get Spectron in our "master" branch, then we can delete this branch here.

**Pull request closed without merging**
