### PR TITLE
Added Dutch language

### PR DESCRIPTION
**Pull request by mvdwoord**
Hi, I added Dutch language. I do not have the resource right now to run the tests, also not very experienced in pull requests, hope I did everything alright. If you need me to amend something, just let me know.

### CODE REVIEW

**Comment by lipis** [comment]
Thank you for that...As we are dealing with translations on [Crowdin](https://crowdin.com/project/wire-cs) to avoid conflicts and mistakes we would like the contributors for languages to contribute directly there instead of PR to avoid future [mistakes](https://github.com/wireapp/wire-desktop/pull/204#issuecomment-262570984)

**Comment by lipis** [comment]
Also we need to reach 100% on Dutch to continue with it.. https://crowdin.com/project/wire-cs/nl#

**Comment by mvdwoord** [comment]
That makes sense, I just noticed the update in Italian and decided to add dutch. I'll check out crowdin.

**Comment by mvdwoord** [comment]
Requested to join the translation team on crowdin.

**Comment by mvdwoord** [comment]
Is there a guide for contributors somewhere, where to contribute what?

**Comment by lipis** [comment]
Yes you are right about Italian and it was my bad that I didn't notice it..

Here is a small guide.. http://brand.wire.com/text/translation/#top

**Comment by lipis** [comment]
I'm sorry, but we will close this issue as we have an automated process of getting new translations from Crowdin..

**Pull request closed without merging**
