### PR TITLE
Update amplify call for preferences

### PR DESCRIPTION
**Pull request by gregor**

### CODE REVIEW

**Comment by gregor** [comment]
Merging this now as the new preferences have made it into staging

**Comment by herrmannplatz** [comment]
Is this backwards compatible?

**Comment by gregor** [comment]
Should be. The old call is still referenced in https://github.com/wireapp/wire-webapp/blob/dev/app/script/view_model/list/ListViewModel.coffee#L61. Can be removed once uptake of new version is high enough. Not sure how this is related to WEBAPP-3267

**Comment by gregor** [comment]
Tried to keep backwards compatibility in mind with all the changes but apparently missed it in some places. We need to come up with a better strategy to keep track of the depencies between wire-desktop and wire-webapp moving forward.

**Pull request merged**
