### PR TITLE
Add option to start minimized

### PR DESCRIPTION
**Pull request by ConorIA**
Adds a checkbox to the 'Window' menu to start the app in the tray (i.e. skip `main.show()` on startup.)
This partially addresses #104. 

I'm not sure what is going on in the Windows menu, so I didn't touch that, but I feel pretty confident about the code for macOS. Tried, tested and true on Linux, of course!

### CODE REVIEW

**Comment by shvchk** [comment]
Would be nice to have this as an argument, like `--minimized`, so that Wire could be added to autostart to be launched minimized, and showed as usual if launched manually.

**Comment by ConorIA** [comment]
I'm not entirely sure what the `--startup` flag is for, but if it is `true`, I think the app window won't show. It is on the same line as the change I made in this PR. @lipis, is this used anywhere else in the app?

**Comment by ConorIA** [comment]
Come to think of it, my guess is that that flag is precisely for when you want Wire to launch on startup.  😌

**Comment by shvchk** [comment]
Ha! There really is `if (!argv.startup)` check before `main.show()`, thanks for the tip!

**Comment by ConorIA** [comment]
Thanks for the suggestion. It's addressed in the last couple of commits.

**Comment by ConorIA** [comment]
Updated to include newer changes.

**Comment by lipis** [comment]
Handled in #329

**Pull request closed without merging**
