### PR TITLE
Change package name to avoid conflicts

### PR DESCRIPTION
**Pull request by lipis**
Round two on #442

### CODE REVIEW

**Comment by ffflorian** [comment]
When installing the app as `wire-desktop` while having `wire` installed, I get this error:
```
Unpacking wire-desktop (2.11.2721) ...
dpkg: error processing archive wire-desktop_2.11.2721_amd64.deb (--install):
 trying to overwrite '/opt/Wire/libffmpeg.so', which is also in package wire 2.11.2721
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 wire-desktop_2.11.2721_amd64.deb
```

This means I have to uninstall `wire` first and thus losing all local data. As @lipis reported, it also changes the filename on Windows...

**Comment by lipis** [comment]
We might want to put a hold on this one.. :(

**Comment by lipis** [comment]
As it's it will delete the history.. we might deal with it when fixing the PPA package #430.

**Comment by mythsunwind** [comment]
PR was replaced by #550

**Pull request closed without merging**
