### PR TITLE
chore: Update electron to version 3.0.8 (WEBAPP-5468)

### PR DESCRIPTION
**Pull request by gregor**
Updating electron to version 3.0.6 to get the benefit of running version 66 of Google Chrome

**THE END**

### CODE REVIEW

**Comment by lipis** [comment]
@ffflorian  Go to sleep! :P

**Comment by gregor** [comment]
> I receive this message on startup:
> 
> ```
> electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
> ```

As mentioned in the known issues list in internal chat.

**Comment by ffflorian** [comment]
Needs some more fixes before merging.

**Comment by atomrc** [comment]
@ffflorian could you list somewhere (In the PR probably) what are the fixes that are still necessary for the PR to be mergeable? (At least the few you have in mind)

**Comment by ffflorian** [comment]
@atomrc The fixes are in now :stuck_out_tongue: 
@pwnsdx can you please check the failing tests?

**Comment by bennyn** [comment]
From the development side we are good to go with this PR but before we merge it to "master" we need to create a build on Jenkins from this branch which we can then send to test automation. This has been discussed with @mythsunwind and will be done next week. So please don't merge it for now.

**Comment by ffflorian** [comment]
Works fine on Linux :+1:

**Pull request merged**
