### PR TITLE
Debian postinst link script

### PR DESCRIPTION
**Pull request by ConorIA**
Adds a `postinst` script to the .deb packages to link `/opt/wire/wire` to `/usr/bin/wire`.
Adds a `postrm` script to the .deb packages to remove `/usr/bin/wire`. 
Addresses #160.

### Test .debs
- [64-bit](https://cloud.conr.ca/s/rATacZKeahIgHS7/download)
- [32-bit](https://cloud.conr.ca/s/8R9dLXsEtp0j6nZ/download)

### postinst
``` 
#!/bin/bash

# Link to the binary
ln -sf '/opt/wire/wire' '/usr/bin/wire'
```
### postrm
``` 
#!/bin/bash

# Delete the link to the binary
rm -f '/usr/bin/wire'
```

P.S. I wasn't sure where to stick the scripts in the repo folder hierarchy. I'm happy to move them if needs be.

### CODE REVIEW

**Comment by lipis** [comment]
awesome.. maybe under bin folder? /bin/deb or /bin/linux?

**Comment by lipis** [comment]
I'm guessing it works with AppImage as well or only deb?

**Comment by ConorIA** [comment]
Only deb, I think. If a user wants their AppImage on their path, they should just stick the AppImage itself in /usr/local/bin, I think.

**Comment by lipis** [comment]
or to put it differently.. it won't break anything with AppImage..?

**Comment by ConorIA** [comment]
Not as far as I can tell. I tested the AppImage after making the changes. It only inserts a script into the debian control archive; it doesn't actually add anything to the unpacked dir and so I imagine nothing changes in the AppImage either. The AppImage is running fine for me. Just built.

**Comment by lipis** [comment]
bq_udn3cyaaliky

**Comment by jphebus** [comment]
The postinst script wrongly links /usr/bin/wire to /opt/**w**ire/wire rather than to /opt/**W**ire/wire (case matters on most Linux filesystems). Wire currently installs to /opt/Wire/. It might be better to just have Wire install to /opt/wire/, all lowercase.

This occurs in the most recent 64-bit deb package: wire_2.11.2685_amd64.deb

**Comment by ConorIA** [comment]
Changed here: https://github.com/electron-userland/electron-builder/commit/2906227d9cd41a3d2e131d5233ee897968c01b5b. PR on the way.

**Pull request merged**
