### PR TITLE
#296 Implement 'Copy' context menu functionality

### LINKED ISSUE #296: Copy context menu has no effect
On Ubuntu 16.04 with Wire 2.11.2670, if you right click a message there is a context menu with the single option "Copy." Presumably this is intended to copy the message. However, there is no change to the text on the clipboard.

### PR DESCRIPTION
**Pull request by maximbaz**
Fixes #296.
Works with multi-line text and code blocks.

### CODE REVIEW

**Comment by lipis** [comment]
shalle we maybe reset the `copyContext = '';` somewhere in the beginning of the `contextmenu` event listener?

**Comment by maximbaz** [comment]
sure :)

**Comment by lipis** [comment]
Travis is slow today.. (again)

**Comment by lipis** [comment]
💃 🍻 👍

**Pull request merged**
