### PR TITLE
Flash icon in taskbar on new messages (Windows)

### PR DESCRIPTION
**Pull request by mythsunwind**

### CODE REVIEW

**Comment by lipis** [comment]
👍 nice one :)

**Comment by gregor** [comment]
@lipis @mythsunwind Very nice and we definitely have to improve in this area but why did we merge right away? This is a design/interaction decision. I doubt we want the icon to be flashing the whole time... How are other messaging apps handling this?

**Comment by lipis** [comment]
@gregor you have a point here.. but it's not flashy all the time but only for a few seconds on the first message.. so it's quite nice. Did you try it?

**Comment by gregor** [comment]
No, not yet. I will give it a try today and compare the interaction with other apps.

**Comment by lipis** [comment]
Sure! Let us know and maybe show it to Yorgos.. :)

**Pull request merged**
