### PR TITLE
Added Danish locale

### PR DESCRIPTION
**Pull request by Strit**
I made the Danish locale here.

Is it possible to do for the android-app too?

### CODE REVIEW

**Comment by lipis** [comment]
Hey.. thanks for that.. but for the translations from now on we will only accept contributions on Crowdin.. https://crowdin.com/project/wire-cs/da

And from here you can find more clients to translate: https://crowdin.com/projects/wire

**Comment by Strit** [comment]
That fair.

**Comment by lipis** [comment]
Tak!

(Yes I merged this one: https://github.com/wireapp/wire-desktop/pull/204 and realized afterwards that it wasn't from Crowdin)

**Comment by Strit** [comment]
I see on Crowdin that danish is almost finished. Would be great to have it both on desktop and android.

**Comment by lipis** [comment]
Wire for Web should be translated as well before we continue with the Desktop: https://crowdin.com/project/wire-cs/da#. 

As for Android I'll ping them to check the status :)

**Comment by hakonbo** [comment]
@Strit  @lipis Next Android release should have Danish translation included.

**Pull request closed without merging**
